language: ruby
sudo: required
rvm:
  - 2.2
before_install:
  - curl -sL https://sentry.io/get-cli/ | bash
  - gem update bundler
  - bundle install
script:
  - sentry-cli info --config-status-json
  - bundle exec rubocop
  - rspec
